version: "3"
services:
  app:
    container_name: ${PROJECT_NAME}
    build:
      context: ./setup/node
      args:
        - NODE_VER=${NODE_VER}
        - HOSTS_URL=${HOSTS_URL}
    volumes:
      - ./app:/app
    ports:
      - "3000:10000"
    extra_hosts:
      - "${HOSTS_URL}:${IP_DISPATCH}"
