version: "3"
services:
  app:
    container_name:
    build:
      context:  ./setup/node
      args:
        - NODE_VER=${NODE_VER}
        - BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./app:/app
    ports:
      - "3000:10000"
    extra_hosts:
      - "${BACKEND_URL}:${IP_DISPATCH}"
