version: "3"
services:
  app:
    container_name: ${PROJECT_NAME}
    build:
      context: ./setup/node
      args:
        - NODE_VER=${NODE_VER}
    environment:
      - MAGENTO_BACKEND_URL=${BACKEND_URL}
    volumes:
      - ./app:/app
    ports:
      - "3000:10000"
    extra_hosts:
      - "jrstg.local:192.168.1.45"
